config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'recipes#index'
  resources :recipes, only: %i(index show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef
  attr_accessor :name

  def initialize(name)
    @name = name
  end
end

app/models/recipe.rb
class Recipe

  attr_accessor :id, :title, :description, :image, :chef, :tags

  def initialize(id, title, image, description = nil, chef = nil, tags = nil)
    @id = id
    @title = title
    @image = image
    @description = description if description.present?
    @chef = Chef.new(chef) if chef.present?
    @tags = tags.each { |tag| Tag.new(tag) } if tags.present?
  end

  def self.load(recipe_id)
    recipe = client.entry(recipe_id)
    chef = recipe.chef.name if recipe.fields.key?(:chef)
    tags = recipe.tags.map(&:name) if recipe.fields.key?(:tags)
    Recipe.new(recipe.id, recipe.title, recipe.photo.url, recipe.description, chef, tags)
  end

  def self.all
    ObjectSpace.each_object(self).to_a
  end

  def self.load_recipes
    GC.start
    client.entries(content_type: 'recipe').each do |recipe|
      Recipe.new(recipe.id, recipe.title, recipe.photo.url)
    end
  end

  def self.client
    @client ||= Contentful::Client.new(
      access_token: ENV['contentful_access_token'],
      space: ENV['contentful_space_id']
    )
  end
end

app/models/tag.rb
class Tag
  attr_accessor :name

  def initialize(name)
    @name = name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :load_recipes, only: :index
  before_action :set_recipe, only: :show

  def index
    @recipes = Recipe.all
  end

  def show; end

  private

  def load_recipes
    Recipe.load_recipes
  end

  def set_recipe
    @recipe = Recipe.load(params['id'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContentfulRecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1> Recipes </h1>

<section class="index-page">
  <% @recipes.each do |recipe| %>
    <%= link_to recipe_path(recipe.id) do %>
      <div class="main-div">
        <%= image_tag recipe.image, size: "260x180" %>
        <div class='sub-div'>
          <%= recipe.title %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/recipes/show.html.erb
<section class="show-page">
  <div class="image-div">
    <%= image_tag(@recipe.image, :size => "400x300") %>
  </div>
  <div class="content-div">
    <ul>
      <li><u>Title:</u> <b><%= @recipe.title %></b>
      <li><u>Description:</u> <%= @recipe.description %></b>
      <li><u>List of Tags:</u> <%= @recipe.tags.present? ? @recipe.tags&.join(', ') : '-' %>
      <li><u>Chef name:</u> <%= @recipe.chef.present? ? @recipe.chef&.name : '-' %>
    </ul>
  </div>
</section>
<div class='back-button'>
  <%= link_to '< Back', root_path %>
<div